name: promos_feed_fschmatz
description: Flutter project.
publish_to: 'none'
version: 1.5.4

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http:
  path_provider:
  provider:
  shared_preferences:
  share:
  url_launcher:
  webfeed:
  jiffy:
  easy_dynamic_theme:
  web_scraper:
  flutter_lints: ^1.0.0
  dynamic_color: ^1.6.9
  fluttertoast:

flutter:
  uses-material-design: true
  assets:
    - assets/