name: promos_feed_fschmatz
description: Flutter project.
publish_to: 'none'
version: 1.5.7

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http:
  path_provider:
  provider:
  shared_preferences:
  share_plus: ^10.0.0
  url_launcher:
  webfeed:
  jiffy:
  easy_dynamic_theme:
  web_scraper:
  dynamic_color: ^1.7.0
  fluttertoast:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/